name: Wikilinks
version: "1.0"
description: 'Autolinks content wrapped in [braces], like a wiki.'
url: https://statamic.com/marketplace/addons/wikilinks
developer: Statamic
developer_url: https://statamic.com
